apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hf
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hfuser
  namespace: hf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hf-role
  namespace: hf
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/log
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resourceNames:
  - hf-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hf-role-binding
  namespace: hf
roleRef:
  apiGroup: ""
  kind: Role
  name: hf-role
subjects:
- kind: ServiceAccount
  name: hfuser
  namespace: hf
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hflserver
  namespace: hf
spec:
  ports:
  - name: api-service-port
    nodePort: 30001
    port: 8888
    targetPort: 0
  selector:
    app: hflserver
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hflserver
    product_family: hf
    release: 0.1.0
  name: hflserver
  namespace: hf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hflserver
      product_family: hf
      release: 0.1.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hflserver
        product_family: hf
        release: 0.1.0
      name: hflserver
      namespace: hf
    spec:
      containers:
      - env:
        - name: HFLOW_ROOT
          value: /home/hflow
        - name: DB_BUCKET_PREFIX
          value: hflow_master
        - name: STORAGE_TARGET
          value: GCS
        - name: WORKER_IMAGE
          value: hflow/worker
        - name: IMAGE_PULL_SECRET
        - name: WORKER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: VERSION
          value: 0.1.0
        - name: LOG_LEVEL
        - name: HF_SERVER_CONFIG_VARS
          valueFrom:
            secretKeyRef:
              key: config
              name: hf-secret
              optional: true
        image: hflow/server:0.1.0
        imagePullPolicy: IfNotPresent
        name: hflserver
        ports:
        - containerPort: 8888
          name: api-server-port
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 128M
        volumeMounts:
        - mountPath: /hflow
          name: hflow
        - mountPath: /var/data
          name: db-storage
      serviceAccountName: hfuser
      volumes:
      - name: hflow
      - emptyDir: {}
        name: db-storage
status: {}
---
apiVersion: v1
data:
  config: eyJQdWJsaWNJbnRlcmZhY2UiOiIiLCJNYXN0ZXJJcCI6IiIsIk1hc3RlclBvcnQiOjg4ODgsIk1hc3RlckV4dGVybmFsUG9ydCI6MzAwMDEsIk5vU1NMIjp0cnVlLCJEQiI6eyJEcml2ZXIiOiJCQURHRVIiLCJOYW1lIjoiaGZsb3dfbWFzdGVyIiwiVXNlciI6IiIsIlBhc3MiOiIiLCJEYXRhRGlyUGF0aCI6Ii92YXIvZGF0YSJ9LCJLOCI6eyJOYW1lc3BhY2UiOiJoZiIsIlBhdGgiOiIiLCJJbkNsdXN0ZXIiOnRydWV9LCJPYmpTdG9yYWdlIjp7IlN0b3JhZ2VUYXJnZXQiOiJHQ1MiLCJCYXNlRGlyIjoiaHlwZXJmbG93IiwiUzMiOnsiQ3JlZFBhdGgiOiIiLCJBY2Nlc3NLZXkiOiIiLCJTZWNyZXRLZXkiOiIiLCJTZXNzaW9uVG9rZW4iOiIiLCJCdWNrZXQiOiJoeXBlcmZsb3ciLCJSZWdpb24iOiJ1cy13ZXN0LTIiLCJDcmVkcyI6IiJ9LCJHY3MiOnsiQ3JlZHNQYXRoIjoiIiwiQnVja2V0IjoiaHlwZXJmbG93MDAxIiwiQ3JlZHMiOiJld29nSUNKMGVYQmxJam9nSW5ObGNuWnBZMlZmWVdOamIzVnVkQ0lzQ2lBZ0luQnliMnBsWTNSZmFXUWlPaUFpWVcxd2JHRmljeTEzWldJaUxBb2dJQ0p3Y21sMllYUmxYMnRsZVY5cFpDSTZJQ0kzTldRd05qQmxPRFF4T1dFNU1EZ3paamxoTVRGak16VXpNVFF4WTJFNU0ySXdNV1U0TlRRMklpd0tJQ0FpY0hKcGRtRjBaVjlyWlhraU9pQWlMUzB0TFMxQ1JVZEpUaUJRVWtsV1FWUkZJRXRGV1MwdExTMHRYRzVOU1VsRmRsRkpRa0ZFUVU1Q1oydHhhR3RwUnpsM01FSkJVVVZHUVVGVFEwSkxZM2RuWjFOcVFXZEZRVUZ2U1VKQlVVTmtlRTVITmpOUVFXWjJObVpMWEc1dlJHWjFabVl6SzJVMlZWQnBUMjlpWkM5d01sbEVhVE5IZWpaT2VEbGFWbGgzWkhBNEwyczNiVXhWZEZoaFdFRnliRXh1ZVdjM1Z5dDNTMlF6ZWswMVhHNU9TbmRqYlc5VGFGcHJaVGxhVUVFdlFVSnBhRFZNTldoNVVHbHZiWFJFY2xCTGJYSnVOVE5WV2xZekx6Qm9kemhLUWtkbFJVc3ZNVFpWVFZsWk5sbzBYRzR5Ymk5TU5qQnRUVVV5YUhjMGMwUk9lbVp2YmpNMlVEZFliMkptTlZONU0wZFpTVmgwYW5SSGRYaGtja3hVSzNnM1pIcEpjREpEY0VOQ1l6ZENjR2d5WEc1SWJsTjNZVzV4UmpWUWJISnVSR2h3VjJwNE5sazRTbVIyTVdOdlNGcHJkSE00YjJKcVMyVjRaMGt4VG5oVGRteE5WMnRUYmpReVEyUk9WbXM0VGpSWVhHNXVkell3VkU1bk4zWTVNMGN6ZUc0MWJUbGFjQ3RqU0VKVlJURTNNMmxpWXk5c1NtVndXV3ROZVRaNFpFTjZNVk5zTDFJeFRtMXphR0pxT1hCUGQwMUlYRzVITjJ0U2RVaDRWRUZuVFVKQlFVVkRaMmRGUVV4YVkwVmlRbFZSU201NVFtaHBTVXRTTldGTk5GRTNiSGRpYkRCMlVEbE5iSGQ0ZWtaNVdpdFRkMWx0WEc1UU5FVTBZVlIxYUVZNFIyNURWR0kwWjA1a1prTmhMM1l6WkhWdVFTdDJUbkEwWnpKWVIxZHBWV1ZzTW1KYWNGQmxhMVZUTWxOV05taHNUa2N4TmtneFhHNUpVMVJyWlhJeWFrcEJPSFYyU2tGQmNreG9XR2gxSzFocFZqUm5hakZ0YzJJeGRtdGtaemRHY2k4MmFuWlpjMjh6T0M5WWNUbEpTMVp6WTFndmJtRk5YRzV1ZDNGTFJVZDJPVXBOYmtObFRVZEVOVU51V25aaGJEWjNiRWxRUVVoUVZWRlphV0pRYm13M2RVeHRWRk53VEM5M1dXNURPVFZ5VFZaMlYyVmFVVEpZWEc1UVEzaFNjakU1U0RkeFpXTlROM0IyYjJ4TmJYUnBRbE5oWjNNeVVUYzBNM0pYVjBZNFNITktjeXRZVEhKYU1tOXlNbFY2VEhOa2RUUXlkemxCUVV4aFhHNUxhVE5qTTFSRVZYUmxSMHBUZUVGclNqaHFRMHBvWTJGTlNUSkRlbTVWTUVOMlJIRndVSFZzYjFGTFFtZFJSRmxsYjFGVlduazBOVEl5YVdodFVXZG5YRzQzT1ZGMmIyZFBXbnBVTjNGV0sxZGtWMWR1UjNaT1drMDVURzlRY21oeVVXTm1hVUZpYVhGWGIwRTJXa1ZGUW5NNEsyUnVNVXN3V1V0bFJWcFBOVGt5WEc0clRVMHhUR1I2ZVRKa01ERTBSV1Y0TjB0S1RXcHFLemxKU21oMmRucEJRVkU0VmtGQ1l5OUVhSEJKUjBaU1R6WklSWFpvU1ZOVWJuUlRkMlJWY3pCdFhHNDFXaXROWWtjeGFsRkdNWE5RWkdSeVVVbFNRamR4V2taeFVVdENaMUZETm10dFpuZHFheko1Um1obUswSlBjMFJFVWt4UWFGRTNLMmgzZFZabGVVOUVYRzVRY2xKNk5VUmFORlZXUjNWcWNUQktabmxyTlV4V1JuTkxOR3hqVWxCWGFURlpaVWR6Y1RKaWRWVlJlVU5EYkVsME5FeGxPVk5GTkhKVWFIUlBRbUp4WEc0NWNIQndZMlE1ZDNSNFRUSm5ZMGt4TlU5cGFuTlhlR3h2VVdaa1RUZ3lOR2hSUTBsMVJURm1VV1ppYkVab1ExSXJjbE5vUTI1cE4wNW1NRk5FWjBKUVhHNTFWbFJPU0Vrd00yMTNTMEpuUVVjd1ZsUXphalJvVmt0cFVGSmplRUpsWlZNNGJHdFBVM05KTVhGdU5YSjZSV2c1ZUdNNVpsZEtNWFYwUmsxNVlVWkRYRzVvU0ZwbFdqWTVkalo1TWtKV01FTkZWM2h2VTB4d2NUSkhZazlrUzBwQ1JGQlRXVFpEYW1SUVVqbExXWGhZWlRsTFZHNDFSa3c1YTJSck4wczNjRWhTWEc0NWMyVmxVa0pwUTBGeWVGSm9hVzg0T1hOMk5pdDBUbTlPWTFNeFZtcEJjMDV4YkdkWlUzZGhOR0ZHYzJsNmJXODVSMGRuWnpKaGFFRnZSMEpCU1c5RlhHNVFha2M1UVRSeWJsQjVOV2h6ZG5sYU1Hb3lSRzR2YWpSTE9FTlVla1Y1VG5WWE5ERTVNMjFCU25BeWNqTkRUek5XZFZvclQwMXdPVlp0Y2xWa1MxaFdYRzV6YVVWYU1ITllkRUZ3TjBWWVRUTXpUM2t2TWxKSVNYQTJhVVZhY1doS09VSlFUbGRGYzFoUFIwdzVjM1JDSzNOVE9VTXdUVzk2YmpFcmNIbEtVa0ZKWEc1RE9FbFpTRTU1U0RkeU1pOVhaR2w2YW5GWVNFZHNUR0psUnlzdmRtTnJPRkExYUZGTk9FNWlRVzlIUVVSNVNYSnpPREJNWlUxclIxa3pVVEpSYjJoalhHNXhURlEyYlRCT0wzaGhka0o2WjNnMFNWSXlXREphYTA5d1pVSTJZbmw0YUZCdGFVSlhSM05sTDBoTmFYbHJaRTFuYm00NFJIcHJNa0pZTUdOSVVVZ3hYRzVIUkZKcGEwMDVZak5pVkZKbFlsTjJjSGhxUTBVNFIyRm9ieXRGZUdnNWFsbFJhR2RRUnk4cmFYb3lORW81TTNRd2RIaGlTVXBoVWxrMVJuWm5SbFJrWEc1VVdYTkZiRFl2SzFOaVYwUTFTa2xpTVhkdVdtaFNWVDFjYmkwdExTMHRSVTVFSUZCU1NWWkJWRVVnUzBWWkxTMHRMUzFjYmlJc0NpQWdJbU5zYVdWdWRGOWxiV0ZwYkNJNklDSm9lWEJsY25acFpYY3RjM1J2Y21GblpVQmhiWEJzWVdKekxYZGxZaTVwWVcwdVozTmxjblpwWTJWaFkyTnZkVzUwTG1OdmJTSXNDaUFnSW1Oc2FXVnVkRjlwWkNJNklDSXhNREEyTkRJNU16VXlPRGcyTWpJME9UazBORGdpTEFvZ0lDSmhkWFJvWDNWeWFTSTZJQ0pvZEhSd2N6b3ZMMkZqWTI5MWJuUnpMbWR2YjJkc1pTNWpiMjB2Ynk5dllYVjBhREl2WVhWMGFDSXNDaUFnSW5SdmEyVnVYM1Z5YVNJNklDSm9kSFJ3Y3pvdkwyRmpZMjkxYm5SekxtZHZiMmRzWlM1amIyMHZieTl2WVhWMGFESXZkRzlyWlc0aUxBb2dJQ0poZFhSb1gzQnliM1pwWkdWeVgzZzFNRGxmWTJWeWRGOTFjbXdpT2lBaWFIUjBjSE02THk5M2QzY3VaMjl2WjJ4bFlYQnBjeTVqYjIwdmIyRjFkR2d5TDNZeEwyTmxjblJ6SWl3S0lDQWlZMnhwWlc1MFgzZzFNRGxmWTJWeWRGOTFjbXdpT2lBaWFIUjBjSE02THk5M2QzY3VaMjl2WjJ4bFlYQnBjeTVqYjIwdmNtOWliM1F2ZGpFdmJXVjBZV1JoZEdFdmVEVXdPUzlvZVhCbGNuWnBaWGN0YzNSdmNtRm5aU1UwTUdGdGNHeGhZbk10ZDJWaUxtbGhiUzVuYzJWeWRtbGpaV0ZqWTI5MWJuUXVZMjl0SWdwOUNnPT0ifX0sIkxvZ0xldmVsIjoiNSIsIkxvZ1BhdGgiOiIifQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: hf-secret
    product_family: hf
    release: 0.1.0
  name: hf-secret
  namespace: hf
---
